common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'

urlpatterns=[
    #path('login/', auth_views.LoginView.as_view(), name='login')
    path('login/', auth_views.LoginView.as_view(
        template_name = 'common/login.html' 
        #registration/login.html 대신 templates/common/login.html을 참조하기 위함
    ), name = "login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name="signup")
]

django_server/urls.py
from django.contrib import admin
from django.urls import path,include
from pybo import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    #path('pybo/', views.index)
    path('pybo/', include('pybo.urls')), #pybo 뒤에 오는 애들은 pybo 폴더의 urls.py에 관련짓는다
    path('common/', include('common.urls')),
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
        path('', views.index, name = "index"),
        path('<int:question_id>/', views.detail, name="detail"),
        path('answer/create/<int:question_id>/', views.answer_create, name= "answer_create"),
        path('question/create/', views.question_create, name = "question_create"),
        path('question/modify/<int:question_id>', views.question_modify, name="question_modify"),
        path('question/delete/<int:question_id>', views.question_delete, name='question_delete'),
    ]

common/models.py
from django.db import models

# Create your models here.

pybo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null = True, blank = True)
    
    def __str__(self):
        return self.subject
    
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null = True, blank = True)
    
    

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

pybo/forms.py
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question #사용할 모델
        fields = ['subject', 'content'] #QuestionForm에서 사용할 Question 모델의 속성
        
        #QuestionForm에 부트스트랩 적용을 위해 추가
        # widgets = { #이름도 곡 "widgets" 여야 함
        #     'subject' : forms.TextInput(attrs={'class' : 'form-control'}),
        #     'content' : forms.Textarea(attrs={'class' : 'form-control', 'rows' : 10}),
        # }
        
        labels= { # 영어로 나오는걸 한글로 바꾸고 싶다면
            'subject' : '제목',
            'content' : '내용',
        }
        
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields =['content']
        labels={
            'content' :'답변내용',
        }

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm

# Create your views here.
def signup(request):
    """
        계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password = raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form':form})
            

django_server/views.py
from django.shortcuts import redirect
def index(request):
    return redirect('pybo/')

pybo/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
#from django.http import HttpResponse
from .models import Question
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    """
        pybo 목록 출력
    """
    
    #입력 파라미터
    page = request.GET.get('page', '1') #페이지
    #pybo/?page=1 처럼 get방식으로 호출된 url에서 page값을 가져오는데 사용
    # 만약 pybo/ 처럼 page값 없이 호출된다면 디폴트 1
    #조회
    question_list = Question.objects.order_by('-create_date')
    
    #페이징처리
    paginator = Paginator(question_list, 10) #페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    
    context = {'question_list' : page_obj}
    return render(request, 'pybo/question_list.html', context)
    #return HttpResponse("Welcome to Pybo!")
    
def detail(request, question_id):
    """
        pybo 내용 출력
    """
    question = get_object_or_404(Question, pk = question_id)
    context = {'question' : question}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url = 'common:login')
def answer_create(request,question_id):
    ## 질문 등록하기 버튼 과 저장하기 버튼 둘다 question_create를 호출함 : 구분을 post와 get으로 한다.
    """
        pybo 답변등록 : post
        get 은 그냥 형식 통일상 ㅇㅇ
    """
    #post
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST) #request.POST 에는 subject와 content가 들어있음
        if form.is_valid():
            answer = form.save(commit=False) # 임시저장 : creat_date 정보가 없기 때문
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question_id)
    else:
        form = AnswerForm() #get
    context = {'form' : form, 'question' :question}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url = 'common:login')
def question_create(request):
    ## 질문 등록하기 버튼 과 저장하기 버튼 둘다 question_create를 호출함 : 구분을 post와 get으로 한다.
    """
        pybo 질문등록 : 질문등록 함수를 호출할 때 '저장하기'버튼 : post
        '질문 등록하기' 버튼 : get 
    """
    #post
    
    if request.method == 'POST':
        form = QuestionForm(request.POST) #request.POST 에는 subject와 content가 들어있음
        if form.is_valid():
            question = form.save(commit=False) # 임시저장 : creat_date 정보가 없기 때문
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm() #get
    context = {'form' : form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url = 'common:login')
def question_modify(request, question_id):
    """
        pybo 질문수정
    """
    
    question = get_object_or_404(Question, pk = question_id)
    if request.user != question.author:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('pybo:detail', question_id = question_id)
    
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question) 
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id = question_id)
    else:
        form = QuestionForm(instance=question)  # form생성시 폼의 속성 값이 instance 값으로 채워짐
                                                # 질문을 수정하는 화면에서 제목과 내용이 채워진 채로 보여짐                                                   
        
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url="common:login")        
def question_delete(request, question_id):
    """
        pybo 질문삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제 권한이 없습니다')
        return redirect('pybo:detail', question_id = question.id)
    question.delete()
    return redirect('pybo:index')

templates/base.html
{% load static %}

<html lang = "ko">
<head>
    <!-- Required meta tags -->
    <meta charset = "utf-8">
    <meta name = "viewport" content="widh=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS-->
    <link rel = "stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <title> Hello, pybo! </title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start-->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End-->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<!-- 자바스크립트 Start-->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End-->
</body>
</html>

templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<div class = "container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{next}}"> <!-- 로그인 성공 후 이동되는 url-->
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                    value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="text" class="form-control" name="password" id="password"
                    value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <!--{{ form.as_p }} <!-- subject, content속성에 해당하는 html 코드를 자동으로 생성 -->
        <button type="submit" class="btn btn-primary">로그인</button>
    </form> 
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class = "container my-3">
    <div class="row">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                    value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="text" class="form-control" name="password1" id="password1"
                    value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="text" class="form-control" name="password2" id="password2"
                    value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                    value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <!--{{ form.as_p }} <!-- subject, content속성에 해당하는 html 코드를 자동으로 생성 -->
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form> 
</div>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
    {% for field in form %} <!-- 필드 오류 출력-->
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %} <!-- 넌필드 오류를 출력한다 -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}
        

templates/main.html
<html>
    <title> welcome to my server!</title>
    <body>
        <div>
            <ul>
                <li><a href = "/pybo/">GO TO PYBO</a></li>
                <li><a href = "/admin/">GO TO ADMIN</a></li>
            </ul>
        </div>
    </body>
</html>

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class ="nav-link" href="{% url 'common:logout' %}">{{user.username}}(로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

templates/pybo/question_detail.html
{% extends 'base.html' %}
<!-- 스타일 적용-->
<!-- {% load static %}
<link rel = "stylesheet" type = "text/css" href = "{% static 'bootstrap.min.css' %}"
-->
{% block content %}
<div class ="container my-3">
    <!-- 사용자오류 표시 -->
    {% if messages %}
    <div class = "alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 사용자오류 표시 끝 -->
    <h2 class = "border-bottom-py-2">{{question.subject}}</h2>
    <div class = "card my-3">
        <div class="card-body">
            <p class="card-text" style="white-space: pre-line;">{{question.content}}</p>
                <div class="d-flex justify-content-end">
                    <div class="badge badge-light p-2 text-left">
                        <div class = "mb-2"> {{question.author.username}}</div>
                        <div>{{question.create_date}}</div>
                    </div>
                </div>         
        </div>
        {% if request.user == question.author %}
        <div class = "my-3">
            <a href="{% url 'pybo:question_modify' question.id %}"
                class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#"
                class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:question_delete' question.id %}">삭제</a>
                <!-- data-uri는 제이쿼리에서 $(this).data('uri')를 사용해 그 값을 얻을 수 있다, 확인창 띄우기 위함-->
            </a>
        </div>
        {% endif %}
    </div>
    <!-- ------------------------------------------------------------------------------------- -->
    <h5 class = "border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all reversed %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{answer.content}}</div>
            <div class ="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                    <div class = "mb-2"> {{question.author.username}}</div>
                    <div> {{question.create_date}} </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action ="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="danger">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 end -->
        <div class ="form-group">  
            <textarea {% if not user.is_authenticated %}disabled{% endif %} name = "content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type = "submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
    $(document).ready(function(){
        $(".delete").on('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")){
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock script %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class = "container">
    <h5 class = "my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}

        <!-- 오류표시 start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="danger">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 end -->

        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                    value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="subject">내용</label>
            <textarea class="form-control" name="content" id="content"
                    rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <!--{{ form.as_p }} <!-- subject, content속성에 해당하는 html 코드를 자동으로 생성 -->
        <button type="submit" class="btn btn-primary">저장하기</button> <!-- button 속성에 action="{% url 'pybo:question_create'%}"-->
        <!-- 안했음 : url을 안할 경우 default값으로 현재 페이지(question_create이니까 question/create/)가 정해져 버튼을 누를경우 현재 페이지로
        데이터 전송됨-->
        <!-- 그런데 이렇게 안할 경우 다른 페이지에서 이 버튼을 누르게 할 경우 일일이 지정해 줄 필요 없이 자기 자신 페이지로 돌아가게 하기위해
        일부러 비워두는 것임. (질문 수정도 이걸로 할거임)-->
    </form> 
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}

{% load pybo_filter %}
<!-- {% load static %}
<link rel = "stylesheet" type="text/css" href = "{% static 'bootstrap.min.css'%}">
-->

{% block content %}
<div class = "container my-3">
<table class="table">
    <thead>
        <tr class = "text-center thead-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
    </thead>
    <tbody>
        {% if question_list %} 
            {% for question in question_list reversed %}
                <tr class = "text-center">
                    <!-- index = all - start - now + 1-->
                    <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
                    <td class = "text-left">
                        <a href = "{% url 'pybo:detail' question.id %}">{{question.subject}}</a>
                        {% if question.answer_set.count > 0 %}
                        <span class="text-danger small ml-2">{{question.answer_set.count}}</span>
                        {% endif %}
                    </td>
                    <td>{{ question.author.username }}</td>
                    <td>{{ question.create_date}}</td>
                </tr>
                <!--
                    전체건수	question_list.paginator.count
                    시작인덱스	question_list.start_index
                    현재인덱스	forloop.counter0
                -->
            {% endfor %}
        {% else %}
        <tr>
            <td coldspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
    </tbody>
</table>
<!-- 페이징처리 시작-->
<ul class = "pagination justify-content-center">
    <a class = "page-link" href="?page=1">처음</a>
    <!-- 이전페이지 -->
    {% if question_list.has_previous %}
    <li class = "page-item">
        <a class="page-link" href="?page={{ question_list.previous_page_number  }}">이전</a>
    </li>
    {% else %}
    <li class = "page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in question_list.paginator.page_range %}
    {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class = "page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class = "page-item">
            <a class = "page-link" href="?page={{ page_number }}">{{page_number}}</a>
        </li>
        {% endif %}
    {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if question_list.has_next %}
    <li class = "page-item">
        <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
    </li>
    {% else %}
    <li class = "page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
    <a class = "page-link" href="?page={{ question_list.paginator.num_pages }}">마지막</a>
</ul>
<!-- 페이징처리 끝-->

<a href = "{% url 'pybo:question_create' %}" class="btn btn-primary"> 질문 등록하기</a> <!-- get요청 -->
</div>
{% endblock %}